print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")
print("▀▄▀▄▀▄ Reza Bomber ▄▀▄▀▄▀")
print("-=▀▄▀▄▀▄ ReZa▄▀▄▀▄▀=-")
print("  -=▀▄▀▄▀▄▄▀▄▀▄▀=-")